[theme]
primaryColor = "#E07A5F"
backgroundColor = "#FFF3EE"
secondaryBackgroundColor = "#F7E5DE"
textColor = "#3D3431"
font = "sans serif"

[client]
showSidebarNavigation = true
toolbarMode = "minimal"